CREATE TABLE unidad (
    unidad_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero_unidad VARCHAR(20) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    estado VARCHAR(30) NOT NULL,

    CONSTRAINT pk_unidad PRIMARY KEY (unidad_id),
    CONSTRAINT uq_unidad_numero UNIQUE (numero_unidad)
);

CREATE TABLE persona (
    persona_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    correo_electronico VARCHAR(150) NOT NULL,

    CONSTRAINT pk_persona PRIMARY KEY (persona_id),
    CONSTRAINT uq_persona_correo UNIQUE (correo_electronico)
);

CREATE TABLE area_comun (
    area_comun_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    capacidad INTEGER NOT NULL,
    estado VARCHAR(30) NOT NULL,

    CONSTRAINT pk_area_comun PRIMARY KEY (area_comun_id),
    CONSTRAINT uq_area_comun_nombre UNIQUE (nombre),
    CONSTRAINT ck_area_comun_capacidad CHECK (capacidad > 0)
);

CREATE TABLE residencia (
    residencia_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    persona_id BIGINT NOT NULL,
    unidad_id BIGINT NOT NULL,

    CONSTRAINT pk_residencia PRIMARY KEY (residencia_id),
    CONSTRAINT fk_residencia_persona
        FOREIGN KEY (persona_id)
        REFERENCES persona(persona_id),
    CONSTRAINT fk_residencia_unidad
        FOREIGN KEY (unidad_id)
        REFERENCES unidad(unidad_id)
);

CREATE TABLE reserva (
    reserva_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    area_comun_id BIGINT NOT NULL,
    persona_id BIGINT NOT NULL,
    fecha_inicio TIMESTAMPTZ NOT NULL,
    fecha_fin TIMESTAMPTZ NOT NULL,
    estado VARCHAR(30) NOT NULL,

    CONSTRAINT pk_reserva PRIMARY KEY (reserva_id),
    CONSTRAINT fk_reserva_area_comun
        FOREIGN KEY (area_comun_id)
        REFERENCES area_comun(area_comun_id),
    CONSTRAINT fk_reserva_persona
        FOREIGN KEY (persona_id)
        REFERENCES persona(persona_id),
    CONSTRAINT ck_reserva_fechas
        CHECK (fecha_fin > fecha_inicio)
);